version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend  # Adjust this path to where your frontend code is
    ports:
      - "3000:80"  # Maps port 80 in the container to 3000 on your host
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend  # Adjust this path to where your backend code is
    ports:
      - "5000:5000"  # Maps port 5000 in the container to 5000 on your host
    environment:
      - NODE_ENV=production
      # Add other environment variables your backend needs
      # - DATABASE_URL=...
      # - API_KEY=...