version: '3.8'

services:
  frontend:
    build: 
      context: ./email-spam-frontend  # Updated to match your directory name
      dockerfile: dockerfile.frontend  # If using named Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend  # Assuming this is still named "backend"
      dockerfile: dockerfile.backend  # If using named Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production