version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/email-spam-detection  # Replace with your DB name

  frontend:
    build:
      context: ./email-spam-frontend
      dockerfile: dockerfile.frontend
    ports:
      - "3000:80"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
